before_script:
  - "mysql -e 'create database bookyt_test;'"
  - DB=mysql bundle exec rake bookyt:setup
  - DB=mysql bundle exec rake db:schema:load

script: "bundle exec rake test"

# whitelist
branches:
  only:
    - master
    - stable

rvm:
  - 1.8.7 # (current default)

bundler_args: "--binstubs --without development"

# IRC notification
notifications:
  irc: "irc.freenode.org#cyt"
