# Database configuration
# ======================
# This file can be use as a template for the database.yml file.
#
# If you're using the SQLite3 file-based database, all you have
# to do is copy this file to database.yml.
#
# For production environments MySQL is a better fit. In this
# case you need to setup the databases and adapt this file:
#
# 1. create the database and grant access
# 2. change the '*sqlite' instances in the Environments section
#    to '*mysql'
# 3. update host, username and password settings in the 'Common
#    settings' section

# Common settings
# ===============
# SQLite3 for ruby
sqlite: &sqlite
  adapter: sqlite3
  pool:    5
  timeout: 5000

# SQLite3 for jruby
jruby_sqlite: &jruby_sqlite
  adapter: jdbcsqlite3
  pool: 5
  timeout: 5000

# MySQL for ruby
mysql: &mysql
  adapter:  mysql
  pool:     5
  timeout:  5000
  host:     localhost
  username: bookyt
  password: REPLACE WITH PWD
  encoding: utf8 

# Environments
# ============
production:
  database: C:\bookyt\production.sqlite3
  <<: *jruby_sqlite

development:
  database: C:\bookyt\development.sqlite3
  <<: *jruby_sqlite

demo:
  database: C:\bookyt\demo.sqlite3
  <<: *jruby_sqlite

test:
  database: C:\bookyt\test.sqlite3
  <<: *jruby_sqlite
